name: Build & Publish Docfx

on:
  schedule:
    - cron: "0 0 * * 0"

jobs:
  docfx:
   runs-on: ubuntu-latest
   steps:
    - name: Build
      uses: ./.github/workflows/build.yml

    - name: Build DocFX
      uses: nikeee/docfx-action@v1.0.0
      with:
        args: Content.Docfx/docfx.json

    - name: Publish Docfx Documentation on GitHub Pages
      uses: maxheld83/ghpages@master
      env:
        BUILD_DIR: Content.Docfx/_content-site
        GH_PAT: ${{ secrets.GH_PAT }}
